spring:
  rabbitmq:
    addresses: 47.98.116.157
    port: 5672
    username: sxli
    password: 123456
  application:
    name: rabbit-mq-dsrect-producer
server:
  port: 8082

rabbitmq:
  config:
    exchange: log.direct
    routing:
      info: log.info.routing.key
      error: log.error.routing.key