spring:
  rabbitmq:
    addresses: 47.98.116.157
    port: 5672
    username: sxli
    password: 123456
  application:
    name: rabbit-mq-dlx-producer
server:
  port: 8082

rabbitmq:
  config:
    exchange: exchange.log