spring:
  rabbitmq:
    addresses: 47.98.116.157
    port: 5672
    username: sxli
    password: 123456
    listener:
      retry:
        enabled: true
        max-attempts: 5
  application:
    name: rabbit-mq-ack-consumer
server:
  port: 8083

rabbitmq:
  config:
    exchange: exchange.ack
    routing:
      ack: routing.ack
      noack: routing.no.ack