spring:
  rabbitmq:
    addresses: 47.98.116.157
    port: 5672
    username: sxli
    password: 123456
  application:
    name: rabbit-mq-fanout-consumer
server:
  port: 8083

rabbitmq:
  config:
    exchange: order.fanout